# Generated by Django 4.0.1 on 2022-01-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('publish_date', models.DateField()),
                ('body', models.TextField()),
                ('preview_body', models.CharField(max_length=250)),
                ('img_url', models.CharField(blank=True, max_length=125, null=True)),
            ],
            options={
                'ordering': ('-publish_date',),
            },
        ),
    ]
