# Generated by Django 4.0.1 on 2022-01-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_article_img_url_alter_article_preview_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='preview_body',
            field=models.TextField(),
        ),
    ]
