# Generated by Django 4.0.1 on 2022-01-12 11:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_en', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('content_ru', ckeditor.fields.RichTextField(verbose_name='Содержимое')),
            ],
        ),
    ]
