# Generated by Django 4.0.1 on 2022-01-12 13:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_en', ckeditor.fields.RichTextField(verbose_name='Content English version')),
                ('content_ru', ckeditor.fields.RichTextField(verbose_name='Содержимое русской версии сайта')),
            ],
        ),
        migrations.DeleteModel(
            name='site',
        ),
    ]
