# Generated by Django 4.0.1 on 2022-01-14 13:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_integration', '0002_service_delete_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_en', ckeditor.fields.RichTextField(verbose_name='English version content "About company"')),
                ('content_ru', ckeditor.fields.RichTextField(verbose_name='Содержимое "О компании" русской версии сайта')),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='content_en',
            field=ckeditor.fields.RichTextField(verbose_name='English version content of "Services"'),
        ),
        migrations.AlterField(
            model_name='service',
            name='content_ru',
            field=ckeditor.fields.RichTextField(verbose_name='Содержимое "Услуг" русской версии сайта'),
        ),
    ]
