# Generated by Django 4.0.1 on 2022-01-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_integration', '0003_aboutcompany_alter_service_content_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='sub_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='service',
            name='sub_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
    ]
