# Generated by Django 4.0.1 on 2022-01-14 14:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_integration', '0004_service_sub_title_en_service_sub_title_ru'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTitleService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title_ru', models.CharField(max_length=255, verbose_name='Подзаголовок страницы услуг на русском')),
                ('sub_title_en', models.CharField(max_length=255, verbose_name='Подзаголовок страницы услуг на английском')),
            ],
        ),
        migrations.RemoveField(
            model_name='aboutcompany',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='aboutcompany',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='service',
            name='sub_title_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='sub_title_ru',
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='body_en',
            field=ckeditor.fields.RichTextField(default='asd', verbose_name='Содержимое "О компании" на английском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='body_ru',
            field=ckeditor.fields.RichTextField(default='das', verbose_name='Содержимое "О компании" на русском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='sub_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='sub_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='service',
            name='img',
            field=models.ImageField(default='dsa', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(default='ads', max_length=255, verbose_name='Название услуг на английском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='title_ru',
            field=models.CharField(default='das', max_length=255, verbose_name='Название услуги на русском'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='content_en',
            field=ckeditor.fields.RichTextField(verbose_name='Текст услуги на английском'),
        ),
        migrations.AlterField(
            model_name='service',
            name='content_ru',
            field=ckeditor.fields.RichTextField(verbose_name='Текст услуги ан русском'),
        ),
    ]
