# Generated by Django 4.0.1 on 2022-01-14 17:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_integration', '0005_subtitleservice_remove_aboutcompany_content_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompanyOnIndexPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_en', ckeditor.fields.RichTextField(verbose_name='Текст на главной странице в блоке о компании на английском')),
                ('content_ru', ckeditor.fields.RichTextField(verbose_name='Текст на главной странице в блоке о компании на русском')),
            ],
            options={
                'verbose_name_plural': 'Блок "О компании" на главной странице',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_ru', models.CharField(max_length=255, verbose_name='Адрес, который отображается в футере и на странице контактов в русской версии')),
                ('address_en', models.CharField(max_length=255, verbose_name='Адрес, который отображается в футере и на странице контактов в английском версии')),
                ('legal_address_ru', models.CharField(max_length=255, verbose_name='Юредический адрес, который отображается в футере и на странице контактов в русской версии')),
                ('legal_address_en', models.CharField(max_length=255, verbose_name='Юредический адрес, который отображается в футере и на странице контактов в английской версии')),
                ('working_time_ru', models.CharField(max_length=255, verbose_name='Время работы, которое отображается в футере и на странице контактов')),
                ('working_time_en', models.CharField(max_length=255, verbose_name='Время работы, которое отображается в футере и на странице контактов в русской версии')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Номера телефонов, которое отображается в футере и на странице контактов')),
                ('email', models.EmailField(max_length=255, verbose_name='email, который отображается в футере и на странице контактов')),
                ('full_name_ru', models.CharField(max_length=255, verbose_name='Полное наименование, который отображается в футере и на странице контактов в русской версии')),
                ('full_name_en', models.CharField(max_length=255, verbose_name='Полное наименование, который отображается в футере и на странице контактов в английской версии')),
                ('UNP', models.CharField(max_length=255, verbose_name='УНП, который отображается в футере и на странице контактов')),
            ],
            options={
                'verbose_name_plural': 'Контакты. Отображаются на странице контакты и в футоре',
            },
        ),
        migrations.RenameModel(
            old_name='SubTitleService',
            new_name='ServiceSubTitle',
        ),
        migrations.AlterModelOptions(
            name='aboutcompany',
            options={'verbose_name_plural': 'Страница "О компании"'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'Услуги. Услуг может быть больше одной'},
        ),
        migrations.AlterModelOptions(
            name='servicesubtitle',
            options={'verbose_name_plural': 'Текст на странице услуг'},
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='sub_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовк на английском'),
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='sub_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок на русском'),
        ),
    ]
