# Generated by Django 4.0.1 on 2022-01-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_integration', '0006_aboutcompanyonindexpage_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSubTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title_ru', models.CharField(max_length=255, verbose_name='Подзаголовок страницы новостей на русском')),
                ('sub_title_en', models.CharField(max_length=255, verbose_name='Подзаголовок страницы новостей на английском')),
            ],
            options={
                'verbose_name_plural': 'Страница "Новости". Текст в верху страницы',
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Страница "Контакты" и "Футер"'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'Список услуг'},
        ),
        migrations.AlterModelOptions(
            name='servicesubtitle',
            options={'verbose_name_plural': 'Страница "Услуги". Текст в верху страницы'},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='UNP',
        ),
        migrations.AddField(
            model_name='contact',
            name='unp',
            field=models.CharField(default=12321321312132, max_length=255, verbose_name='УНП'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='address_en',
            field=models.CharField(max_length=255, verbose_name='Адрес, английский'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address_ru',
            field=models.CharField(max_length=255, verbose_name='Адрес, русский'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='full_name_en',
            field=models.CharField(max_length=255, verbose_name='Полное наименование, английский'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='full_name_ru',
            field=models.CharField(max_length=255, verbose_name='Полное наименование, русский'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='legal_address_en',
            field=models.CharField(max_length=255, verbose_name='Юридический адрес, английский'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='legal_address_ru',
            field=models.CharField(max_length=255, verbose_name='Юридический адрес, русский'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=255, verbose_name='Номера телефонов'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='working_time_en',
            field=models.CharField(max_length=255, verbose_name='Время работы, английский'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='working_time_ru',
            field=models.CharField(max_length=255, verbose_name='Время работы, русский'),
        ),
    ]
