# Generated by Django 4.0.1 on 2022-01-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_integration', '0007_newssubtitle_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', models.CharField(max_length=255, verbose_name='Текст страницы услуг на русском')),
                ('text_en', models.CharField(max_length=255, verbose_name='Текст страницы услуг на английском')),
            ],
            options={
                'verbose_name_plural': 'Страница "Услуги". Текст в верху страницы',
            },
        ),
        migrations.DeleteModel(
            name='ServiceSubTitle',
        ),
    ]
