# Generated by Django 4.0.1 on 2022-01-15 14:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_integration', '0008_servicetext_delete_servicesubtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutcompany',
            name='body_en',
        ),
        migrations.RemoveField(
            model_name='aboutcompany',
            name='body_ru',
        ),
        migrations.RemoveField(
            model_name='aboutcompany',
            name='sub_title_en',
        ),
        migrations.RemoveField(
            model_name='aboutcompany',
            name='sub_title_ru',
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='body_1_en',
            field=ckeditor.fields.RichTextField(default='sad', verbose_name='Текст 1 блока на английском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='body_1_ru',
            field=ckeditor.fields.RichTextField(default='ads', verbose_name='Текст 1 блока на русском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='body_2_en',
            field=ckeditor.fields.RichTextField(default='das', verbose_name='Текст 2 блока на английском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='body_2_ru',
            field=ckeditor.fields.RichTextField(default='das', verbose_name='Текст 2 блока на русском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='sub_title_1_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок 1 блока на английском'),
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='sub_title_1_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок 1 блока на русском'),
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='sub_title_2_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок 2 блока на английском'),
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='sub_title_2_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок 2 блока на русском'),
        ),
    ]
