# Generated by Django 4.0.1 on 2022-01-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_integration', '0009_remove_aboutcompany_body_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcompany',
            name='sub_title_1_en',
            field=models.CharField(default='test', max_length=255, verbose_name='Подзаголовок 1 блока на английском'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='sub_title_1_ru',
            field=models.CharField(default='test', max_length=255, verbose_name='Подзаголовок 1 блока на русском'),
            preserve_default=False,
        ),
    ]
