# Generated by Django 4.0.1 on 2022-01-23 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_integration', '0012_aboutcompany_text_with_blue_backgroun_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutcompany',
            old_name='text_with_blue_backgroun_en',
            new_name='text_with_blue_background_en',
        ),
        migrations.RenameField(
            model_name='aboutcompany',
            old_name='text_with_blue_backgroun_ru',
            new_name='text_with_blue_background_ru',
        ),
    ]
