# Generated by Django 4.0.1 on 2022-01-24 08:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_integration', '0014_alter_servicetext_text_en_alter_servicetext_text_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='content_ru',
        ),
        migrations.AddField(
            model_name='service',
            name='content_1_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст 1 абзаца услуги на английском'),
        ),
        migrations.AddField(
            model_name='service',
            name='content_1_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст 1 абзаца услуги ан русском'),
        ),
        migrations.AddField(
            model_name='service',
            name='content_2_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст 2 абзаца услуги на английском'),
        ),
        migrations.AddField(
            model_name='service',
            name='content_2_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст 2 абзаца услуги ан русском'),
        ),
        migrations.AddField(
            model_name='service',
            name='content_3_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст 3 абзаца услуги на английском'),
        ),
        migrations.AddField(
            model_name='service',
            name='content_3_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст 3 абзаца услуги ан русском'),
        ),
    ]
