# Generated by Django 4.0.1 on 2022-01-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_integration', '0015_remove_service_content_en_remove_service_content_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number_1',
            field=models.CharField(default='+375 (174) 323323', max_length=255, verbose_name='1 номер телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number_2',
            field=models.CharField(default='+375 (29) 6253512', max_length=255, verbose_name='2 номер телефона'),
            preserve_default=False,
        ),
    ]
