# Generated by Django 4.0.1 on 2022-01-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_integration', '0016_remove_contact_phone_number_contact_phone_number_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='preview_en',
            field=models.CharField(default='name of service', max_length=255, verbose_name='Превью услуги на английском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='preview_ru',
            field=models.CharField(default='name of service', max_length=255, verbose_name='Превью услуги на русском'),
            preserve_default=False,
        ),
    ]
