# Generated by Django 4.0.1 on 2022-02-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_integration', '0017_service_preview_en_service_preview_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='preview_en',
            field=models.TextField(verbose_name='Превью услуги на английском'),
        ),
        migrations.AlterField(
            model_name='service',
            name='preview_ru',
            field=models.TextField(verbose_name='Превью услуги на русском'),
        ),
    ]
