# Generated by Django 4.0.1 on 2022-02-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_integration', '0020_service_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Название услуги в адресной строке'),
        ),
    ]
